version: '{branch}-rev{build}'

shallow_clone: true

skip_commits:
  files:
    - .travis.yml
    - Doxyfile
    - LICENSE
    - License-Cabin.txt
    - Logo.png
    - LogoMini.png
    - readme.md
    - readme_fr.md
    - 'writing style.md'
    - doc/*
    - NazaraModuleTemplate/*

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

install:
  - cd build && "./premake5.exe" %TOOLSET% && cd ..

configuration:
  - DebugDynamic
  - ReleaseDynamic

platform:
  - Win32
  - x64

build:
  project: build/$(TOOLSET)/NazaraEngine.sln

after_build:
  - cd build && "./premake5.exe" package && cd ../package
  - 7z a NazaraEngine.7z * && cd ..
  
artifacts:
  - path: package/NazaraEngine.7z
    name: 'NazaraEngine-$(CONFIGURATION)-$(PLATFORM)-$(APPVEYOR_REPO_COMMIT)'

on_success:
  - cd tests && "./NazaraUnitTestsServer.exe"

notifications:
  - provider: Slack
  incoming_webhook:
    secure: 5FSnJzsZCMXNDqPYGhN4ZSX7qa1KMmbV0UGT9i0LcElk3X91z3fs1TZRpZZ3++Tkw8qAk1G/qDChom5GQ7Vj7X29cScQHvGHXffl3qaC5EdSiGpjloMZKfeiGTnf798IX0n/ABSlDHG7GrB8IiulRGx3iVOpPQmrPWCiz9ZPtY8h84xpd65FGd8gETKG/sYk